---
- include: postgresql.yml
  when: web_frontend == 'nginx'

- include: mysql.yml
  when: web_frontend == 'apache'

- name: Template of Flow.json
  template:
    src: Flow.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/Flow.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    id: "{{qbroker_service_id}}" 
    qb_dir: "{{qbroker_dir}}"
    log_dir: "{{tomcat_logdir}}"
  notify: Restart_tomcat.service

- name: Template of node_collect.json
  template:
    src: node_collect.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/node_collect.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    db_type: "{{ 'postgresql' if web_frontend == 'nginx' else 'mysql' }}"
  notify: Restart_tomcat.service

- name: Template of pstr_db_query.json for postgresql
  template:
    src: pstr_db_query.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/pstr_db_query.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    db_type: postgresql
    db_port: "{{postgresql_port}}"
    db_name: "{{postgresql_db_name}}"
    db_user: "{{postgresql_db_user}}"
    db_passwd: "{{postgresql_db_passwd}}"
  when: web_frontend == 'nginx'
  notify: Restart_tomcat.service

- name: Template of pstr_db_query.json for mysql
  template:
    src: pstr_db_query.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/pstr_db_query.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    db_type: mysql
    db_port: "{{mysql_port}}"
    db_name: "{{mysql_db_name}}"
    db_user: "{{mysql_db_user}}"
    db_passwd: "{{mysql_db_passwd}}"
  when: web_frontend == 'apache'
  notify: Restart_tomcat.service
