---
- include: "{{idservice_db}}.yml"
  when: idservice_db_local == True

- name: Template of Flow.json
  template:
    src: Flow.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/Flow.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    id: "{{qbroker_service_id}}"
    qb_dir: "{{qbroker_dir}}"
    log_dir: "{{tomcat_logdir}}"
  notify: Restart_tomcat.service

- name: Template of node_collect.json
  template:
    src: node_collect.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/node_collect.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    db_type: "{{idservice_db}}"
  notify: Restart_tomcat.service

- name: Template of pstr_db_query.json
  template:
    src: pstr_db_query.json.j2
    dest: "{{qbroker_dir}}/flow/{{qbroker_service_id}}/pstr_db_query.json"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
    mode: 0644
  vars:
    db_type: "{{idservice_db}}"
    db_url: "{{idservice_db_url}}"
    db_user: "{{idservice_db_user}}"
    db_passwd: "{{idservice_db_passwd|replace('\n', '')}}"
  notify: Restart_tomcat.service
