---
- include: "{{idservice_db}}.yml"
  when: idservice_db_local == True

- include: "../../qbroker/tasks/webapp_{{webapp_container|default('tomcat')}}.yml"
  vars:
    service_id: "{{idservice_service_id}}"
    webapp_context: "{{role_name}}"
    my_artifact: "{{idservice_artifact}}"
    my_jar_files: "{{idservice_jar_files}}"
    my_jsp_files: "{{idservice_jsp_files}}"
    my_json_files: "{{idservice_json_files}}"
    my_java_opts: "{{idservice_java_opts}}"

- name: Template of Flow.json
  template:
    src: Flow.json.j2
    dest: "{{qbroker_dir}}/flow/{{idservice_service_id}}/Flow.json"
    owner: "{{qbroker_user}}"
    group: "{{qbroker_group}}"
    mode: 0644
  vars:
    id: "{{idservice_service_id}}"
    qb_dir: "{{qbroker_dir}}"
    log_dir: "{{qbroker_dir}}/{{role_name}}/{{idservice_log_folder}}"
  notify: "Restart_{{role_name}}"

- name: Template of node_collect.json
  template:
    src: node_collect.json.j2
    dest: "{{qbroker_dir}}/flow/{{idservice_service_id}}/node_collect.json"
    owner: "{{qbroker_user}}"
    group: "{{qbroker_group}}"
    mode: 0644
  vars:
    db_type: "{{idservice_db}}"
  notify: "Restart_{{role_name}}"

- name: Template of pstr_db_query.json
  template:
    src: pstr_db_query.json.j2
    dest: "{{qbroker_dir}}/flow/{{idservice_service_id}}/pstr_db_query.json"
    owner: "{{qbroker_user}}"
    group: "{{qbroker_group}}"
    mode: 0644
  vars:
    db_type: "{{idservice_db}}"
    db_url: "{{idservice_db_url}}"
    db_user: "{{idservice_db_user}}"
    db_passwd: "{{idservice_db_passwd|replace('\n', '')}}"
  notify: "Restart_{{role_name}}"
