---
- name: Check table of services
  command: /usr/bin/mysql "{{mysql_db_name}}" -e 'show columns from services'
  register: table_check
  failed_when: False
  changed_when: False

- name: Copy mysql_eventid.sql
  copy:
    src: mysql_eventid.sql
    dest: /tmp/
    mode: 0644
  when: "'service_id' not in table_check.stdout"

- name: Load schema of mysql_eventid.sql
  mysql_db:
    name: "{{mysql_db_name}}"
    state: import
    target: /tmp/mysql_eventid.sql
  when: "'service_id' not in table_check.stdout"

- name: Cleanup mysql_eventid.sql
  file:
    path: /tmp/mysql_eventid.sql
    state: absent
