---
- name: Check table of services
  become: yes
  become_user: "{{postgresql_user}}"
  command: /usr/bin/psql "{{postgresql_db_name}}" -c '\d services'
  register: table_check
  failed_when: False
  changed_when: False

- name: Copy eventid.sql
  copy:
    src: eventid.sql
    dest: /tmp/
    mode: 0644
  when: "'service_id' not in table_check.stdout"

- name: Load schema of eventid.sql
  become: yes
  become_user: "{{postgresql_user}}"
  command: /usr/bin/psql "{{postgresql_db_name}}" -f /tmp/eventid.sql
  when: "'service_id' not in table_check.stdout"

- name: Grant privileges on tables
  become: yes
  become_user: "{{postgresql_user}}"
  postgresql_privs:
    database: "{{postgresql_db_name}}"
    role: "{{postgresql_db_user}}"
    type: table
    objs: services,instances,components
    privs: SELECT,UPDATE,INSERT,DELETE
    state: present

- name: Grant privileges on sequences
  become: yes
  become_user: "{{postgresql_user}}"
  postgresql_privs:
    database: "{{postgresql_db_name}}"
    role: "{{postgresql_db_user}}"
    type: sequence
    objs: service_id_seq,instance_id_seq,component_id_seq
    privs: SELECT,UPDATE
    state: present

- name: Cleanup eventid.sql
  file:
    path: /tmp/eventid.sql
    state: absent
