---
- name: Send a rest request to {{qb_service}}
  uri:
    url: "https://{{idservice_server_name|default(ansible_host, true)}}/{{qb_service}}/rest/id/event?name=x:y:z"
    method: GET
    headers:
      Content-type: text/plain
      Host: "{{idservice_server_name|default('localhost', true)}}"
    return_content: yes
    validate_certs: no
  register: query_result
  changed_when: False

- name: Check the response from {{qb_service}}
  assert:
    that:
      - "'\"event_id\":' in query_result.content"
